apps/friendships/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^(?P<user_id>\d+)$', views.view, name="view"),
    url(r'^(?P<friend_id>\d+)/add$', views.add, name="add"),
    url(r'^(?P<friendship_id>\d+)/delete$', views.delete, name="delete"),
    url(r'^(?P<friendship_id>\d+)/accept$', views.accept, name="accept"),
    url(r'^(?P<friendship_id>\d+)/decline$', views.decline, name="decline"),
]

apps/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

friends/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.users.urls', namespace ='users')),
    url(r'^friends/', include('apps.friendships.urls', namespace='friendships'))
]

apps/friendships/models.py
from __future__ import unicode_literals
from django.db import models
from ..users.models import User
# Create your models here.

class FriendManager(models.Manager):
    def create_friendship(self, user_id, friend_id):
        user = User.objects.get(user_id = user_id)
        friend = User.objects.get(user_id = friend_id)
        pass

    def accept_friendship(self, friend):
        pass

class Friend(models.Model):
    user = models.ForeignKey(User, related_name="users_friend")
    friend = models.ForeignKey(User, related_name="friends_friend")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    accepted = models.BooleanField(default=False)

    objects = FriendManager()

apps/users/models.py
from __future__ import unicode_literals
from django.db import models
from django.db import IntegrityError
import bcrypt
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile(r'^[A-Za-z]+$')

class UserManager(models.Manager):
    def validate(self, name, alias, password, password_confirm, email, birthdate):
        errors = []
        if len(name) < 3:
            errors.append("Name must be longer than 2 characters.")
        elif not NAME_REGEX.match(name):
           errors.append("Your name must only contain characters.")
        if len(alias) < 2:
            errors.append("Your Alias must be at least 2 characters.")
        if len(password) < 8:
            errors.append("Password must be at least 8 characters long.")
        if password_confirm != password:
            errors.append("Passwords do not match. Please re-enter your password.")
        if not EMAIL_REGEX.match(email):
            errors.append("Please enter a valid email address.")
        return errors

    def register(self, name, alias, password, email, birthdate):
        errors = []
        try:
            hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
            user = User.objects.create(name=name, alias=alias, password_hash=hashed, email=email, birthday=birthdate)
        except IntegrityError:
            errors.append("That email is already taken.")
            return {'errors': errors}
        return {'user': user}

    def authenticate(self, email, password):
        errors = []
        try:
            user = User.objects.get(email=email)
        except:
            errors.append("Email not found, please register.")
            return {'errors': errors}
        if bcrypt.hashpw(password.encode(), user.password_hash.encode()) == user.password_hash:
            return {'user': user}
        else:
            errors.append("Incorrect password. Please re-enter your password.")
            return {'errors': errors}

class User(models.Model):
    name = models.CharField(max_length=50)
    alias = models.CharField(max_length=25)
    password_hash = models.CharField(max_length=256)
    email = models.CharField(max_length=50, unique=True)
    birthday = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/friendships/views.py
from django.shortcuts import render, redirect
from models import *
# Create your views here.

def index(request):
    if "id" not in request.session:
        return redirect("users:index")
    user_id = request.session['id']
    alias = request.session['alias']
    non_friends = User.objects.exclude(id=user_id).exclude(users_friend__friend=user_id).exclude(friends_friend__user=user_id)
    friends = Friend.objects.filter(user=user_id, accepted=True) | Friend.objects.filter(friend=user_id, accepted=True)
    sent_requests = Friend.objects.filter(user=user_id, accepted=False)
    received_requests = Friend.objects.filter(friend=user_id, accepted=False)
    context = {
        'user_id': user_id,
        'alias': alias,
        'non_friends': non_friends,
        'friends': friends,
        'sent_requests': sent_requests,
        'received_requests': received_requests
    }
    return render(request, "friendships/home.html", context)

def add(request, friend_id):
    user_id = request.session['id']
    user = User.objects.get(id = user_id)
    friend = User.objects.get(id = friend_id)
    Friend.objects.create(user=user, friend=friend)
    # users = Friend.objects.create_friendship(user_id, friend_id)
    return redirect('friendships:home')

def view(request, user_id):
    user= User.objects.get(id=user_id)
    context = {
    "user":user
    }
    return render(request, "friendships/view.html", context)

def delete(request, friendship_id):
    Friend.objects.get(id=friendship_id).delete()
    return redirect("friendships:home")

def accept(request, friendship_id):
    Friend.objects.filter(id=friendship_id).update(accepted=True)
    return redirect("friendships:home")

def decline(request, friendship_id):
    Friend.objects.get(id=friendship_id).delete()
    return redirect("friendships:home")

apps/users/views.py
from django.shortcuts import render, redirect
import datetime
from django.contrib import messages
from models import *

# Create your views here.
def index(request):
    return render(request, 'users/index.html')

def register(request):
    if request.method == "POST":
        name = request.POST['name']
        alias = request.POST['alias']
        email = request.POST['email']
        password = request.POST['password']
        password_confirm = request.POST['password_confirm']
        birthdate = request.POST['birthdate']
        errors = User.objects.validate(name, alias, password, password_confirm, email, birthdate)
        if errors:
            for e in errors:
                messages.add_message(request, e)
        else:
            user = User.objects.register(name, alias, password, email, birthdate)
            if 'errors' in user:
                messages.error(request, user['errors'][0])
            else:
                request.session['id'] = user['user'].id
                request.session['alias'] = user['user'].alias
                return redirect('friendships:home')
        return redirect('users:index')

def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.authenticate(email, password)
        if 'errors' in user:
            messages.error(request, user['errors'][0])
        else:
            request.session['id'] = user['user'].id
            request.session['alias'] = user['user'].alias
            return redirect('friendships:home')
    return redirect('users:index')

def logout(request):
    request.session.clear()
    return redirect('users:index')







# eighteen_years_ago = datetime.date.today() - datetime.timedelta(weeks=totalweeks)

apps/friendships/templates/friendships/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Friends</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'users/styles.css' %}" type="text/css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px|Bubbler+One|Pangolin" rel="stylesheet">

  </head>
  <body>
    <div class="container">
      <div class='col-xs-6'>
        <h2>Hello, {{ alias }}</h2>
      </div>
      <div class='col-xs-6'>
        <a class="logout pull-right" href="{% url 'users:logout' %}">Log Out</a>
      </div>
      <div class="col-xs-12">
        <h4>Here is the list of your friends:</h4>
        <div class="row col-xs-8">
          <table class="table table-striped table-bordered text-center">
            <thead>
              <th class="text-center">Alias</th>
              <th class="text-center">Action</th>
            </thead>
            <tbody>
              {% for friend in friends %}
              <tr>
                {% if friend.friend.id != user_id %}
                <td>{{ friend.friend.alias }}</td>
                {% else %}
                <td>{{ friend.user.alias }}</td>
                {% endif %}
                <td>
                  {% if friend.friend.id != user_id %}
                  <a class="btn btn-primary" href="{% url 'friendships:view' user_id=friend.friend.id %}">View Profile</a>
                  {% else %}
                  <a class="btn btn-primary" href="{% url 'friendships:view' user_id=friend.user.id %}">View Profile</a>
                  {% endif %}
                  <a class="btn btn-danger" href="{% url 'friendships:delete' friendship_id=friend.id %}">Remove as Friend</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="non-friends-div row col-xs-8">
          <h4>Other users not on your friends list:</h4>
          <table class="table table-striped table-bordered text-center">
            <thead>
              <th class="text-center">Alias</th>
              <th class="text-center">Action</th>
            </thead>
            <tbody>
              {% for user in non_friends %}
              <tr>
                <td><a href="{% url 'friendships:view' user_id=user.id %}">{{ user.alias }}</a></td>
                <td><a class="btn btn-primary" href="{% url 'friendships:add' friend_id=user.id %}">Add as friend</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="pending-received col-xs-12 col-md-6">
        <h4>New Friend Requests</h4>
        {% if received_requests %}
        <table class="table table-striped table-bordered text-center">
          <thead>
            <th class="text-center">Alias</th>
            <th class="text-center">Action</th>
          </thead>
          <tbody>
            {% for request in received_requests %}
            <tr>
              <td><a href="{% url 'friendships:view' user_id=request.user.id %}">{{ request.user.alias }}</a></td>
              <td>
                <a class="btn btn-success" href="{% url 'friendships:accept' friendship_id=request.id %}">Accept request</a>
                <a class="btn btn-danger" href="{% url 'friendships:decline' friendship_id=request.id %}">Decline request</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p class="text-info">You have no pending requests</p>
        {% endif %}
      </div>
      <div class="pending-sent col-xs-12 col-md-6">
        <h4>Pending (sent) Requests</h4>
        {% if sent_requests %}
        <table class="table table-striped table-bordered text-center">
          <thead>
            <th class="text-center">Alias</th>
            <th class="text-center">Action</th>
          </thead>
          <tbody>
            {% for request in sent_requests %}
            <tr>
              <td><a href="{% url 'friendships:view' user_id=request.friend.id %}">{{ request.friend.alias }}</a></td>
              <td><a class="btn btn-warning" href="{% url 'friendships:decline' friendship_id=request.id %}">Rescind Request</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p class="text-info">You have no pending requests</p>
        {% endif %}
      </div>
    </div>
  </body>
</html>

apps/friendships/templates/friendships/view.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Friendships</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'users/styles.css' %}" type="text/css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px|Bubbler+One" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="text-right links">
        <a href="{% url 'friendships:home' %}">Home</a>&nbsp;&nbsp;
        <a href="{% url 'users:logout' %}"> Logout</a>
      </div>
      <div>
        <h2>{{user.alias}}'s Profile</h2>
        <h4>Name: {{user.name}}</h4>
        <h4>Email Address: {{user.email}}</h4>
        <h4>Birthday: {{ user.birthday|date:"F d, Y" }}</h4>
      </div>

    </div>
  </body>
</html>

apps/users/templates/users/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Friends App Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'users/styles.css' %}" type="text/css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px|Bubbler+One" rel="stylesheet">
   </head>
  <body>
    <div class="container">
      <h1>Welcome To Friends App!</h1>
      <h3>Please Log In or Register</h3>
      <div id="register" class="col-md-6 col-xs-12">
        <form class="form-horizontal" action="{% url 'users:register'%}" method="post">
          {% csrf_token %}
          <div id="legend">
            <legend class="">Register</legend>
          </div>
          <div class="form-group">
            <label class="col-md-2 control-label" for="name">Name:</label>
            <div class="col-md-10">
              <input class="form-control" type="text" name="name" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-2 control-label" for="alias">Alias:</label>
            <div class="col-md-10">
              <input class="form-control" type="text" name="alias" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-2 control-label" for="email">E-Mail:</label>
            <div class="col-md-10">
              <input class="form-control" type="text" name="email" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-2 control-label" for="password">Password:</label>
            <div class="col-md-10">
              <input class="form-control" type="password" name="password" />
            </div>
          </div>
          <p class="help-block">*Password must be at least 8 characters.</p>
          <div class="form-group">
            <label class="col-md-2 control-label" for="password">Confirm Password:</label>
            <div class="col-md-10">
              <input class="form-control" type="password" name="password_confirm" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-2 control-label" for="birthdate">Date of Birth:</label>
            <div class="col-md-10">
              <input class="form-control" type="date" name="birthdate" />
            </div>
          </div>
          <input class="btn btn-primary form-button" type="submit" value="Register">
        </form>

        {% if messages %}
          {% for m in messages %}
            <div class="alert-message block-message">
              <p class="text-danger">{{m}}</p>
            </div>
          {% endfor %}
        {% endif %}

      </div>
      <div id="login" class="col-md-6 col-xs-12">
        <form class="form-horizontal" action="{% url 'users:login' %}" method="post">
          {% csrf_token %}
          <div id="legend">
            <legend class="">Login</legend>
          </div>
          <div class="form-group">
            <label class="col-md-2 control-label" for="email">E-Mail:</label>
            <div class="col-md-10">
              <input class="form-control" type="text" name="email" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-2 control-label" for="password">Password:</label>
            <div class="col-md-10">
              <input class="form-control" type="password" name="password" />
            </div>
          </div>
          <input class="btn btn-primary form-button" type="submit" value="Log In">
        </form>
      </div>
    </div>
  </body>
</html>